<template>
  <div class="home">
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
    <p>首页</p>
  </div>
</template>
<script>
  export default {
    mounted () {
//      this.$store.commit('setBreadlist', [{path: '/home', meta: {title: '首页'}}]);
    }
  }
</script>
<style lang="scss" scoped>
  .home{

  }
</style>
